insert into public.song_categories(name) values ('legrůtský'),('majstrštyky');
insert into public.songs(name) values
('Ha depa ste šický Potřekovský chlapcí / Žádnyj nám nemůže / Dnes tyjden celyj den'),
('Pode vsí nade vsí dlouhý pole'),
('Jen ty k nám Honzíčku choď'),
('Já se dycky vohlídám'),
('Sem řemesla zednickýho'),
('Pod našima vokny rozkvítá bez'),
('Pivíčko je dobrota'),
('My máme doma černou slepici'),
('Potřekovská chasa, jaká je to krása'),
('Mám já šátek v šosu'),
('Vosum je kůželek'),
('Vyjdu já si na kopeček'),
('Sedum let sem nevidíl'),
('Ve vsi psí štěkají'),
('Bul jest jeren sedlák'),
('Hdyž sem přišel k vám bulo zandáno'),
('Dyž sem já mou milou ponyjprv vidíl / Trumpetří'),
('Ten panckyj mosteček prohyjbá se'),
('Dybych já přesmutná vedíla / Za náši stodolou'),
('Ha ty svatyj Vavřinečku'),
('Nade Klenčím jaluveček'),
('Škály se pukají'),
('Huž se svítá vod Baldova'),
('Jerenáct trubačů'),
('Bořická šenkýřko'),
('Zafoukej větříčku přes ten vrch vzhůru'),
('Hdo nezná Postřekov'),
('Čí je to divčátko'),
('Že to pivo nevypíju'),
('Kmotry'),
('Na tom našom ouvárečku'),
('Vy chasnící, vy myslíte'),
('Pí, Honzíčku, pí'),
('Handělský svoření'),
('Muziky huž táhnou ke dvoru'),
('Hdepa si bul chlapče'),
('Vodbila hodina'),
('Pod vokýnkem sem stával'),
('Šla žena pro muže'),
('Hdyby buly moje'),
('Teče voda'),
('Já bych se voženil'),
('V tý postřekovský hospodě'),
('Čevená růžičko rozvíjej se'),
('Dyť já mou Hančičku znám'),
('V tom Tranově malyj pivovárek'),
('Hdyž sem šel vod milý, skřivánci zpívali'),
('Na tom novým panckým mostě, počítá tám vochčák vochce'),
('Hančička spí'),
('Hdyž sem já šel vod Hančičky'),
('Hdyž sem šel vod milý, pes na mě štěkál'),
('Sedlácí píjou'),
('Hančičko hubičko dyj trošíčku'),
('Dyž sem já ouvrať vorál'),
('Dyž sem já šel vokolo vrat'),
('Nedávyj, Hančičko, nedávyj'),
('Paní mámo zlatá, co děláte');
